spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/ecoshop}  # Puerto 5433 (mapeo Docker: 5433:5432)
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}  # Usa la variable de entorno DB_PASSWORD o actualiza aqu√≠
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.ecoshop: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

